### ISSUE TITLE
Chewett wants a cup of tea

### ISSUE THREAD

**Issue by HarryCutts** [soton-ecs-2014-gdp-12/presentations#2]

**Comment by chewett** [comment]
Still important :P

**Comment by HarryCutts** [comment]
&#9749;

**Comment by HarryCutts** [comment]
(I'd just like to point out that that was supposed to be a [Unicode generic "hot beverage"](http://www.fileformat.info/info/unicode/char/2615/index.htm) before GitHub turned it into coffee.)
